apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.fullname }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.fullname }} 